### ISSUE TITLE
Maybe It's time to write some tests?

### ISSUE THREAD

**Issue by m0sth8** [cocaine/cocaine-framework-go#15]
I think we could add CI tests, Travis CI for example. What do you think?

**Comment by noxiouz** [comment]
> I think we could add CI tests, Travis CI for example. What do you think?

It's done in v0.12. Moreover I try to add tests for a new code.
> I think we could start to use interfaces instead of structs, wherever it's possible.
Service, Request, Response, Logger, Locator are replaced by interfaces. IO uses io.ReadWriterCloser instead of ```net.Conn``` directly. So it's possible (and it's done) to mock network with pipe class.
