### ISSUE TITLE
Possible mistakes

### ISSUE THREAD

**Issue by m0sth8** [cocaine/cocaine-framework-go#21]
At line https://github.com/cocaine/cocaine-framework-go/blob/master/cocaine/asocket.go#L147
we should check count before error, cause 
`
Callers should always process the n > 0 bytes returned before considering the error err. Doing so correctly handles I/O errors that happen after reading some bytes and also both of the allowed EOF behaviors.
`
http://golang.org/pkg/io/#Reader

**Comment by noxiouz** [comment]
There's no such error in v0.12. Should I  fix in v0.11?
