### ISSUE TITLE
Distributing both versions of the framework.

### ISSUE THREAD

**Issue by noxiouz** [cocaine/cocaine-framework-go#29]
I'd like to merge v0.12 into master branch, but it could affect v0.11 clients. I really don't want to use non native version systems like pkg.in. So propose to put both versions in the same repo, but in to different directories. Like cocaine11  & cocaine12. Any thoughts? We can get rid of cocaine11 later.
@m0sth8 @lamerman @mechmind

**Comment by Kobolog** [comment]
Why don't you do diverged branches like in Core?

**Comment by noxiouz** [comment]
@Kobolog  It would break standart stupid mechanism of fetching deps in go. As ```go get``` don't worry about branches, it just makes ```git clone --recursive -b master```, so everyone needs to checkout branch to v0.11 manually.

**Comment by 3Hren** [comment]
It's **go**, remember? They can't use the foreign code just like that: `import github.com/cocaine/cocaine-framework-go/v0.12`.

**Comment by Kobolog** [comment]
![ROFLCOPTER](http://i.giphy.com/77R88c35HIfKM.gif)

**Comment by lamerman** [comment]
It works pretty stupid in Go now, but anyway, to make it work and not break anything maybe creation of new repository for the new incompatible version would be a better way. 
In that new repository you can provide a possibility for further incompatible changes in the future within one repository.
